//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionRequest
    {
        public int Id { get; set; }
        public string T_NAME { get; set; }
        public string T_OWNER_NAME { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
