//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPT_LOGIN_DETAILS
    {
        public int DEPT_ID { get; set; }
        public string DEPT_USERNAME { get; set; }
        public string DEPT_PASS { get; set; }
    }
}
