//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_SERVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MST_SERVICE()
        {
            this.MST_DOC_SERVICE_MPG = new HashSet<MST_DOC_SERVICE_MPG>();
        }
    
        public int S_SERVICE_ID { get; set; }
        public string S_SERVICE_NAME { get; set; }
        public Nullable<bool> S_ACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_DOC_SERVICE_MPG> MST_DOC_SERVICE_MPG { get; set; }
    }
}
