//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_DOC_SERVICE_MPG
    {
        public int MPG_ID { get; set; }
        public Nullable<bool> MPG_ACTIVE { get; set; }
        public Nullable<int> S_SERVICE_ID { get; set; }
        public Nullable<int> DOC_ID { get; set; }
    
        public virtual MST_DOCS MST_DOCS { get; set; }
        public virtual MST_SERVICE MST_SERVICE { get; set; }
    }
}
