//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_STATUS
    {
        public int STATUS_ID { get; set; }
        public string STATUS_TYPE { get; set; }
        public Nullable<int> T_ID { get; set; }
    
        public virtual TRN_REGISTRATION TRN_REGISTRATION { get; set; }
    }
}
