//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MST_DOCS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MST_DOCS()
        {
            this.MST_DOC_SERVICE_MPG = new HashSet<MST_DOC_SERVICE_MPG>();
            this.TRN_THEATRE_DOCS = new HashSet<TRN_THEATRE_DOCS>();
        }
        [Key]
        public int DOC_ID { get; set; }
        public string DOC_NAME { get; set; }
        public Nullable<bool> DOC_ACTIVE { get; set; }
        public Nullable<int> FILE_SIZE_MB { get; set; }
        public string FILE_TYPE { get; set; }
        public Nullable<bool> MANDATORY_FLAG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_DOC_SERVICE_MPG> MST_DOC_SERVICE_MPG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_THEATRE_DOCS> TRN_THEATRE_DOCS { get; set; }
    }
}
