//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NO_OF_SCREENS_LOG
    {
        public int NO_OF_SCREENS_LOG_ID { get; set; }
        public int SCREEN_ID { get; set; }
        public int T_ID { get; set; }
        public Nullable<int> AUDIENCE_CAPACITY { get; set; }
        public string SCREEN_TYPE { get; set; }
        public string ACTION_TYPE { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
    
        public virtual NO_OF_SCREENS NO_OF_SCREENS { get; set; }
        public virtual TRN_REGISTRATION TRN_REGISTRATION { get; set; }
    }
}
