//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENTLIST
    {
        public int P_ID { get; set; }
        public int T_ID { get; set; }
        public string T_NAME { get; set; }
        public string OWNER_NAME { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public string STATUS_PAYMENT { get; set; }
        public decimal AMOUNT { get; set; }
    
        public virtual TRN_REGISTRATION TRN_REGISTRATION { get; set; }
    }
}
