//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_HISTORY
    {
        public int PAYMENT_ID { get; set; }
        public Nullable<int> T_ID { get; set; }
        public string STATUS { get; set; }
        public decimal AMOUNT { get; set; }
        public System.DateTime PAYMENT_DATE { get; set; }
    
        public virtual TRN_REGISTRATION TRN_REGISTRATION { get; set; }
    }
}
