//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PENDING_DUES
    {
        public int DUE_ID { get; set; }
        public string D_MON { get; set; }
        public string D_YEAR { get; set; }
        public string D_STATUS { get; set; }
        public Nullable<bool> D_ACTIVE { get; set; }
    }
}
