//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_FILTER
    {
        public int RCPT_NO { get; set; }
        public System.DateTime RCPT_GEN_DATE { get; set; }
        public Nullable<int> T_ID { get; set; }
        public string PAY_MODE { get; set; }
        public string STATUS { get; set; }
    
        public virtual TRN_REGISTRATION TRN_REGISTRATION { get; set; }
    }
}
