//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenementFacility
    {
        public int TenementFacilityID { get; set; }
        public Nullable<int> TenementID { get; set; }
        public Nullable<int> FacilityID { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Tenement Tenement { get; set; }
    }
}
