//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class THEATER_MODULEEntities : DbContext
    {
        public THEATER_MODULEEntities()
            : base("name=THEATER_MODULEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionRequest> ActionRequests { get; set; }
        public virtual DbSet<DEPARTMENT_LOGIN> DEPARTMENT_LOGIN { get; set; }
        public virtual DbSet<MST_DOC_SERVICE_MPG> MST_DOC_SERVICE_MPG { get; set; }
        public virtual DbSet<MST_DOCS> MST_DOCS { get; set; }
        public virtual DbSet<MST_SERVICE> MST_SERVICE { get; set; }
        public virtual DbSet<NO_OF_SCREENS> NO_OF_SCREENS { get; set; }
        public virtual DbSet<NO_OF_SCREENS_LOG> NO_OF_SCREENS_LOG { get; set; }
        public virtual DbSet<NO_OF_SCREENS_TAX> NO_OF_SCREENS_TAX { get; set; }
        public virtual DbSet<PAYMENT_HISTORY> PAYMENT_HISTORY { get; set; }
        public virtual DbSet<PAYMENTLIST> PAYMENTLISTs { get; set; }
        public virtual DbSet<PENDINGDUEADMIN> PENDINGDUEADMINs { get; set; }
        public virtual DbSet<RECEIPT_FILTER> RECEIPT_FILTER { get; set; }
        public virtual DbSet<T_RECEIPT> T_RECEIPT { get; set; }
        public virtual DbSet<THEATER_TAX_PAYMENT> THEATER_TAX_PAYMENT { get; set; }
        public virtual DbSet<TRN_REGISTRATION> TRN_REGISTRATION { get; set; }
        public virtual DbSet<TRN_REGISTRATION_LOG> TRN_REGISTRATION_LOG { get; set; }
        public virtual DbSet<TRN_THEATRE_DOCS> TRN_THEATRE_DOCS { get; set; }
        public virtual DbSet<TRN_THEATRE_DOCS_LOG> TRN_THEATRE_DOCS_LOG { get; set; }
        public virtual DbSet<USER_LOGIN> USER_LOGIN { get; set; }
        public virtual DbSet<DEPT_LOGIN_DETAILS> DEPT_LOGIN_DETAILS { get; set; }
        public virtual DbSet<LOGIN_DETAILS> LOGIN_DETAILS { get; set; }
        public virtual DbSet<MST_STATUS> MST_STATUS { get; set; }
        public virtual DbSet<PENDING_DUES> PENDING_DUES { get; set; }
        public virtual DbSet<TRN_SCREEN_TAX_PRICE> TRN_SCREEN_TAX_PRICE { get; set; }
    }
}
