//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEATER_TAX_PAYMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THEATER_TAX_PAYMENT()
        {
            this.NO_OF_SCREENS_TAX = new HashSet<NO_OF_SCREENS_TAX>();
        }
    
        public int TAX_ID { get; set; }
        public int T_ID { get; set; }
        public string PAYMENT_MONTH { get; set; }
        public int PAYMENT_YEAR { get; set; }
        public decimal TAX_AMOUNT { get; set; }
        public string SHOW_STATEMENT { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NO_OF_SCREENS_TAX> NO_OF_SCREENS_TAX { get; set; }
        public virtual TRN_REGISTRATION TRN_REGISTRATION { get; set; }
    }
}
