//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_SCREEN_TAX_PRICE
    {
        public int PRICE_ID { get; set; }
        public string SCREEN_TYPE { get; set; }
        public Nullable<int> SCREEN_PRICE { get; set; }
    }
}
