//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC_THEATER_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_REGISTRATION_LOG
    {
        public int TRN_REGISTRATION_LOG_ID { get; set; }
        public int T_ID { get; set; }
        public string ACTION_TYPE { get; set; }
        public string T_NAME { get; set; }
        public string T_ADDRESS { get; set; }
        public Nullable<bool> T_ACTIVE { get; set; }
        public string T_OWNER_NAME { get; set; }
        public Nullable<long> T_OWNER_NUMBER { get; set; }
        public string T_OWNER_EMAIL { get; set; }
        public Nullable<System.DateTime> T_COMMENCEMENT_DATE { get; set; }
        public string T_CITY { get; set; }
        public string T_ZONE { get; set; }
        public string T_WARD { get; set; }
        public string T_TENAMENT_NO { get; set; }
        public string T_PEC_NO { get; set; }
        public string T_PRC_NO { get; set; }
        public Nullable<bool> T_TAX_PAYING_OFFLINE { get; set; }
        public Nullable<int> OFFLINE_TAX_PAYMENT { get; set; }
        public Nullable<System.DateTime> OFFLINE_TAX_PAID_DATE { get; set; }
        public Nullable<System.DateTime> OFFLINE_DUE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string DELETE_USER { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
        public string STATUS { get; set; }
        public string REJECT_REASON { get; set; }
        public Nullable<System.DateTime> LOG_TIMESTAMP { get; set; }
    
        public virtual TRN_REGISTRATION TRN_REGISTRATION { get; set; }
    }
}
